todo/urls.py
from django.urls import path
from .views import (
    RegistView, HomeView, TaskDeleteView,TaskListView,TaskDetailView,TaskUpdateView, check_title)

app_name = 'todo'
urlpatterns = [
    path('',HomeView.as_view(),name='home'),
    path('regist_task/',RegistView.as_view(),name='regist_task'),
    path('task_list/',TaskListView.as_view(),name='task_list'),
    path('task_detail/<int:pk>/',TaskDetailView.as_view(),name='task_detail'),
    path('task_update/<int:pk>/',TaskUpdateView.as_view(),name='task_update'),
    path('task_delete/<int:pk>/',TaskDeleteView.as_view(),name='task_delete'),
    path('check_title/', check_title, name='check_title'),  # タイトル重複チェック用API
    ]
    

todo_project/urls.py
from turtle import home
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('todo/',include('todo.urls')),
    ]

todo/models.py
from django.db import models
from django.core.exceptions import ValidationError
from django.utils.timezone import now

class Task(models.Model):
    title = models.CharField(max_length=50)
    description = models.TextField(blank=True)  # 空白可にする場合は`blank=True`
    expiry = models.DateField()
    created_at = models.DateTimeField(auto_now_add=True)  # auto_now_add=Trueで登録日がnowでDB保存

    def __str__(self):
        return self.title

    class Meta:     
        db_table='task'
    
    def clean_title(self): #titleの重複登録不可
        if Task.objects.filter(title=self.title).exclude(pk=self.pk).exists():
            raise ValidationError("このタスク名は既に登録されています。")

    def clean_expiry(self): #過去の日付を禁止するバリデーション
        if self.expiry < now().date():
            raise ValidationError('過去の日付は設定できません')

    def clean(self):  # フィールド全体のバリデーションをまとめる
        self.clean_title()  # `clean_title()` を実行
        self.clean_expiry()  # `clean_expiry()` を実行    

todo/forms.py
from django import forms
from .models import Task

class RegistForm(forms.ModelForm):
    title = forms.CharField(label='タスク名')
    description = forms.CharField(label='詳細説明') 
    expiry = forms.DateField(
    label='期限',widget=forms.DateInput(attrs={'class': 'datepicker', 'placeholder': 'YYYY-MM-DD'}))

    class Meta:
        model = Task
        fields = ['title','description','expiry']

class UpdateForm(forms.ModelForm):
    title = forms.CharField(label='タスク名')
    description = forms.CharField(label='詳細説明')
    expiry = forms.DateField(
    label='期限',widget=forms.DateInput(attrs={'class': 'datepicker', 'placeholder': 'YYYY-MM-DD'}))

    class Meta:
        model = Task
        fields = ['title','description','expiry']


    

todo/views.py
from django.urls import reverse_lazy
from .forms import RegistForm, UpdateForm
from .models import Task
from django.shortcuts import render
from django.views.generic import DetailView,CreateView,TemplateView,ListView,DeleteView,UpdateView
from django.http import JsonResponse
from django.db.models import Q

def check_title(request): #入力されたタイトルが既に存在するかを確認
    title = request.GET.get('title')  # フォームの入力値を取得
    exists = Task.objects.filter(title=title).exists()  # タイトルがすでに存在するか確認
    return JsonResponse({'exists':exists})  # exists が True ならタイトルが存在、エラー表示

class HomeView(TemplateView):
    template_name = 'home.html'

class RegistView(CreateView): #taskを追加するページ
    model = Task
    template_name = 'todo/regist_task.html'
    form_class = RegistForm
    success_url = reverse_lazy('todo:home')

class TaskListView(ListView): #task一覧を表示するページ
    model = Task
    template_name = 'todo/task_list.html'
    context_object_name = 'tasks'

    def get_queryset(self):
        query = super().get_queryset()

        #絞り込み・フィルター・並び替え検索のためにクエリを取得しておく
        keyword = self.request.GET.get('keyword', None) 
        task_expiry = self.request.GET.get('task_expiry', None)

        if keyword:
            query = query.filter(Q(title__icontains=keyword) | Q(description__icontains=keyword))

        if task_expiry:
            query = query.filter(expiry=task_expiry)
        

        #★並び替え設定
        sort_options = {
            'created_at':'created_at', #登録した順番(古い順)のsort
            '-created_at':'-created_at', #登録した順番(新しい順)のsort
            'due_date':'expiry' ,  #task期限が早い順のsort
        }   
        # 並び替え基準を辞書(この場合sort_options)で定義
        #sort_optionsは増やすことができる(拡張可能)

        sort_by = self.request.GET.get('sort','-created_at')
        # クエリパラメータ 'sort' を取得（デフォルトは '-created_at'）

        query = query.order_by(sort_options.get(sort_by, 'created_at'))
        #並び替えを設定していない場合はcreated_atで表示(デフォルト設定)

        return query

class TaskDetailView(DetailView):
    model = Task
    template_name = 'todo/task_detail.html'

    def get_context_data(self, **kwargs):
        return super().get_context_data(**kwargs)


class TaskDeleteView(DeleteView): #taskを削除するページ
    model = Task
    template_name = 'todo/task_delete.html'
    success_url = reverse_lazy('todo:task_list')


class TaskUpdateView(UpdateView):
    model = Task
    form_class = UpdateForm
    template_name = 'todo/task_update.html'
    success_url = reverse_lazy('todo:task_list')

templates/base.html
<!DOCTYPE html>
<html lang="ja">
   <head>
      <meta charset="utf-8">
      <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
      <style>
         .navbar-brand {
            margin-bottom: 10px;  /* リンクの間にスペースを追加 */
         }
      </style>
      <link rel="stylesheet" href="https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
      <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
      <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
   </head>
   
   <body>
        Todoアプリ
        <nav class="navbar navbar-expand-lg">
            <a class="navbar-brand" href="{% url 'todo:home' %}">ホーム</a>
            <a class="navbar-brand" href="{% url 'todo:task_list' %}">todoリスト</a>
            <a class="navbar-brand" href="{% url 'todo:regist_task' %}">task作成</a>
        </nav>

        <!-- ナビゲーションとコンテンツの間に余白を追加 -->
        <div style="margin-top: 20px;">
            {% block content %}{% endblock %}
        </div>
   </body>
</html>

templates/home.html
<!DOCTYPE html>
<html lang="ja">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ホーム画面です</title>
</head>

<div>
<nav class="navbar navbar-expand-lg">
    <a class="navbar-brand" href="{% url 'todo:home' %}">ホーム</a>
    <a class="navbar-brand" href="{% url 'todo:task_list' %}">todoリスト</a>
    <a class="navbar-brand" href="{% url 'todo:regist_task' %}">task作成</a> 
</div>

<body>
    ホーム画面です
</body>


</html>

templates/todo/regist_task.html
{% extends 'base.html' %}
{% block content %}
   <form method="POST">
      {% csrf_token %}

      <div>
         タスク名：{{ form.title }}  <!-- タイトル -->
     </div>
     <span id="title_error" style="color:red; display:none;">タイトルがすでに存在します。</span>
      <!-- デフォルト(title空白)がdisplay:none -->
      
      <div>
         説明：{{ form.description }}  <!-- 詳細説明 -->
      </div>
     
      <div>
      期限：{{ form.expiry }} 
      <span id="calendar-icon">📅</span> <!-- カレンダーアイコン -->
      </div>

     <script>
      $(document).ready(function () {
          $(".datepicker").datepicker({
              dateFormat: "yy-mm-dd",
              minDate: 0 // 今日以降の日付のみ選択可能
          });
  
          $("#calendar-icon").click(function () {
              $(".datepicker").focus(); // アイコンをクリックしたら入力欄にフォーカス
          });
      });
  </script>
      
      <input type="submit" value="タスク登録">

      <div>
      <a class="navbar-brand" href="{% url 'todo:task_list' %}">戻る</a>
      </div>
   </form>

   <script>
   document.getElementById('id_title').addEventListener('input', function() {
      var title = this.value;
      
      if (title) {
            // サーバーにタイトルの重複を確認するリクエストを送信
         fetch(`/todo/check_title/?title=${encodeURIComponent(title)}`)
                 // check_titleでviews.pyの関数を呼び出している
                 //ユーザーが入力したタイトルをサーバーに送って、そのタイトルがすでに存在するかどうかを確認する
                 //encodeURIComponentはhtmlとして適切な形にtitleを変換するという意味
                 //クエリパラメータとはwebサーバーに情報を伝えるためにURLに付加する文字列
                 //基本構造は「?」+「変数名(title)」+「=」+「変数の値」で、複数のパラメータがある場合は「&」でつなげる
               .then(response => response.json())  // サーバーから返ってきたデータをJSON形式に変換して、次の処理に渡す
               .then(data => { //サーバーから返ってきたデータ（data）を使って、エラー表示の処理をする//
                  const errorSpan = document.getElementById('title_error');
                  //エラーメッセージを表示するためのHTML要素を取得して変数に保存する//
      
                     // サーバーが `data.exists` を True で返した場合（タイトルが重複している）
                  if (data.exists) {
                        errorSpan.style.display = 'block';} // existsがtrue(同一データ有)ならエラー表示
                     else{ 
                        errorSpan.style.display = 'none';}  // エラー非表示
                     
                  })
                  .catch(error => console.error('Error:', error));  // エラー処理
         }
      });
      </script>
      
   {% endblock %}

templates/todo/task_delete.html
{% extends 'base.html' %}
{% block content %}
<h2>{{ task.title }}/{{ task.expiry }}を削除しますか？</h2>
<form method="POST">
{% csrf_token %}
<a class="navbar-brand" href="{% url 'todo:task_list' %}">戻る</a>
<input type="submit" value="削除">
</form>
{% endblock %}

templates/todo/task_detail.html
{% extends 'base.html' %}
{% block content %}
<h1>TODO Detail</h1>

<form method="GET"
    {% csrf_token %}
    {{ form.as_p }}>
</form>

<table class="table table-striped table-bordered">
<tbody>
    <div>
        <th>タスク名: {{ object.title }}</th>
        <th>説明: {{ object.description }}</th>
        <th>期限: {{object.expiry }}</th>
    </div>
</tbody>
</table>

<tbody>
    <tr>    
        <th><a href="{% url 'todo:task_update' pk=task.id %}" class="btn btn-info">編集</a></th>
        <th><a href="{% url 'todo:task_delete' pk=task.id %}" class="btn btn-danger">削除</a></th>
        <th><a class="navbar-brand" href="{% url 'todo:task_list' %}">戻る</a></th>
    </tr> 
</tbody>

{% endblock %}

templates/todo/task_list.html
    {% extends 'base.html' %}

    {% block content %}
    <h1>TODO LIST</h1>

    <form method="get" action="{% url 'todo:task_list' %}">
        <!-- フォーム内容がここに入る -->
    </form>
    

    <form method="get" action="{% url 'todo:task_list' %}">
        <input type="text" name="keyword" placeholder="タイトルまたは説明で検索" value="{{ request.GET.keyword }}">
        <button type="submit">検索</button><br>
    </form>


    <div>
    <a href="?sort=-created_at">新しい順</a>| 
    <a href="?sort=created_at">古い順</a>| 
    <a href="?sort=due_date">期限順</a> 
    </div>

<div>
    <table class="table table-striped table-bordered">
    <thead>
        <tr>
        <th>タスク名</th>
        <th>期限</th>
        <th>編集</th>
        <th>削除</th>
        </tr> 
    </thead>        
    <tbody>
    {% for task in tasks %}
        <tr>
        <td><a href="{% url 'todo:task_detail' pk=task.id %}">{{ task.title }}</a></td>
        <td>{{ task.expiry }}</td>
        <td><a href="{% url 'todo:task_update' pk=task.id %}" class="btn btn-info">編集</a></td>
        <td><a href="{% url 'todo:task_delete' pk=task.id %}" class="btn btn-danger">削除</a></td>
        </tr>
    {% endfor %} 
    </tbody>
    </table>
</div>
    {% endblock %}      

templates/todo/task_update.html
{% extends 'base.html' %}
{% block content %}
   <form method="POST">
      {% csrf_token %}

      <div>
         タスク名：{{ form.title }}  <!-- タイトル -->
     </div>
     <span id="title_error" style="color:red; display:none;">タイトルがすでに存在します。</span>
      <!-- デフォルト(title空白)がdisplay:none -->
      
      <div>
         説明：{{ form.description }}  <!-- 詳細説明 -->
     </div>
     
     <div>
         期限：{{ form.expiry }}  <!-- 期限 -->
     </div>
      
      <input type="submit" value="タスク登録">
      
      <div>
      <a class="navbar-brand" href="{% url 'todo:task_list' %}">戻る</a>
      </div>
   </form>


<script>
    document.getElementById('id_title').addEventListener('input', function() {
       var title = this.value;
       
       if (title) {
             // サーバーにタイトルの重複を確認するリクエストを送信
          fetch(`/todo/check_title/?title=${encodeURIComponent(title)}`)
                  // check_titleでviews.pyの関数を呼び出している
                  //ユーザーが入力したタイトルをサーバーに送って、そのタイトルがすでに存在するかどうかを確認する
                  //encodeURIComponentはhtmlとして適切な形にtitleを変換するという意味
                  //クエリパラメータとはwebサーバーに情報を伝えるためにURLに付加する文字列
                  //基本構造は「?」+「変数名(title)」+「=」+「変数の値」で、複数のパラメータがある場合は「&」でつなげる
                .then(response => response.json())  // サーバーから返ってきたデータをJSON形式に変換して、次の処理に渡す
                .then(data => { //サーバーから返ってきたデータ（data）を使って、エラー表示の処理をする//
                   const errorSpan = document.getElementById('title_error');
                   //エラーメッセージを表示するためのHTML要素を取得して変数に保存する//
       
                      // サーバーが `data.exists` を True で返した場合（タイトルが重複している）
                   if (data.exists) {
                         errorSpan.style.display = 'block';} // existsがtrue(同一データ有)ならエラー表示
                      else{ 
                         errorSpan.style.display = 'none';}  // エラー非表示
                      
                   })
                   .catch(error => console.error('Error:', error));  // エラー処理
          }
       });
       </script>
       
    {% endblock %}
{% endblock %}  